name: test_workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  project_selector:
    runs-on: ubuntu-latest
    steps:
    - name: get_event
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
        echo "This is a push event to the ${{ github.ref }} branch with the action ${{ github.event.action }}"
        # Add your commands for push event
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "This is a pull request event for the ${{ github.base_ref }} branch to the ${{ github.head_ref }} branch with the action ${{ github.event.action }}"
          # Add your commands for pull request event
        else
          echo "This is an event other than push or pull_request"
          # Add your commands for other events
        fi

    - name: run_labele_steps
      if: contains(${{ github.event.pull_request.labels.*.name  }}, 'bug')
      run: |
        echo "${{ toJson(github.event.pull_request.labels) }}"
        echo "bug label added to the pull request"
        # Add your commands for pull request event
